name: CI/CD with Email Notification and Error File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install > build-log.txt

      - name: Save logs as artifact
        if: ${{ ! cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: build-logs
          path: build-log.txt

      # Add your build and test steps here

  email-notification-success:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() }}

    steps:
      - name: Notify by email (Build Success)
        uses: cinotify/github-action@main
        with:
          to: 'dhanish.ismailharoon@ust.com'
          subject: 'GitHub Actions Build Success'
          body: 'The Build stage of CI/CD workflow is passed.'

  email-notification-failure:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ failure() }}

    steps:
      - name: Download logs artifact
        uses: actions/download-artifact@v2
        with:
          name: build-logs

      - name: Notify by email (Build Failure)
        uses: cinotify/github-action@main
        with:
          to: 'dhanish.ismailharoon@ust.com'
          subject: 'GitHub Actions Build Failure'
          body: 'The Build stage of CI/CD workflow is failed. See attached errors.txt for details.'
          attachment: build-log.txt
