name: CI/CD with Email Notification and Error File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install

      # Add your build and test steps here

  email-notification-success:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() }}

    steps:
      - name: Notify by email (Build Success)
        uses: cinotify/github-action@main
        with:
          to: 'dhanish.ismailharoon@ust.com'
          subject: 'GitHub Actions Build Success'
          body: 'The Build stage of CI/CD workflow is passed.'

  email-notification-failure:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ failure() }}

    steps:
      - name: Save errors to file
        run: |
          echo "----------------" >> errors.txt
          cat $GITHUB_EVENT_PATH >> errors.txt
          echo "----------------" >> errors.txt
          echo "Workflow logs:" >> errors.txt
          echo "----------------" >> errors.txt
        continue-on-error: true

      - name: Notify by email (Build Failure)
        uses: cinotify/github-action@main
        with:
          to: 'dhanish.ismailharoon@ust.com'
          subject: 'GitHub Actions Build Failure'
          body: 'The Build stage of CI/CD workflow is failed. See attached errors.txt for details.'
          attachment: errors.txt
